# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Keep Up' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Keep Up

  target 'Keep UpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Keep UpUITests' do
    # Pods for testing
  end

pod 'Firebase/Analytics'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Charts'


end
